[project]
name = "backend"
version = "0.1.0"
description = "Simple Flask API for the React Vite frontend"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "flask",
  "flask-cors"
]

[tool.uv]
dev-dependencies = []
